// <auto-generated />
using System;
using EbookStore.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EbookStore.Data.Migrations
{
    [DbContext(typeof(EbookStoreDbContext))]
    [Migration("20230215033956_AddBookDescription")]
    partial class AddBookDescription
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.Property<int>("BooksBookId")
                        .HasColumnType("int");

                    b.Property<int>("GenresGenreId")
                        .HasColumnType("int");

                    b.HasKey("BooksBookId", "GenresGenreId");

                    b.HasIndex("GenresGenreId");

                    b.ToTable("BookGenre");
                });

            modelBuilder.Entity("EbookStore.Contract.Model.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("423e533c-d43d-4fd9-9676-e31af724522a"),
                            ConcurrencyStamp = "37e7f001-e332-42a7-a245-c1e126715860",
                            Description = "Administrator role",
                            Name = "Admin",
                            NormalizedName = "admin"
                        },
                        new
                        {
                            Id = new Guid("da35db1a-5b54-4618-884e-bcd7f7b1dd19"),
                            ConcurrencyStamp = "46f6b089-506a-45d8-8e40-f8d6023982a4",
                            Description = "User role",
                            Name = "User",
                            NormalizedName = "user"
                        });
                });

            modelBuilder.Entity("EbookStore.Contract.Model.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"), 1L, 1);

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EpubLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfPage")
                        .HasColumnType("int");

                    b.Property<string>("PdfLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.HasIndex("SaleId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            CoverImage = "cover 1",
                            Description = "Description 1",
                            EpubLink = "EpubLink1",
                            IsActive = true,
                            NumberOfPage = 100,
                            PdfLink = "PdfLink 1",
                            Price = 10.0,
                            ReleaseDate = new DateTime(2023, 2, 15, 10, 39, 55, 492, DateTimeKind.Local).AddTicks(6452),
                            SaleId = 1,
                            Title = "Book 1"
                        },
                        new
                        {
                            BookId = 2,
                            CoverImage = "cover 2",
                            Description = "Description 2",
                            EpubLink = "EpubLink2",
                            IsActive = true,
                            NumberOfPage = 200,
                            PdfLink = "PdfLink 2",
                            Price = 20.0,
                            ReleaseDate = new DateTime(2023, 2, 15, 10, 39, 55, 499, DateTimeKind.Local).AddTicks(5194),
                            SaleId = 2,
                            Title = "Book 2"
                        },
                        new
                        {
                            BookId = 3,
                            CoverImage = "cover 3",
                            Description = "Description 3",
                            EpubLink = "EpubLink3",
                            IsActive = true,
                            NumberOfPage = 300,
                            PdfLink = "PdfLink 3",
                            Price = 30.0,
                            ReleaseDate = new DateTime(2023, 2, 15, 10, 39, 55, 507, DateTimeKind.Local).AddTicks(541),
                            SaleId = 3,
                            Title = "Book 3"
                        },
                        new
                        {
                            BookId = 4,
                            CoverImage = "cover 4",
                            Description = "Description 4",
                            EpubLink = "EpubLink4",
                            IsActive = true,
                            NumberOfPage = 400,
                            PdfLink = "PdfLink 4",
                            Price = 40.0,
                            ReleaseDate = new DateTime(2023, 2, 15, 10, 39, 55, 518, DateTimeKind.Local).AddTicks(8653),
                            SaleId = 4,
                            Title = "Book 4"
                        },
                        new
                        {
                            BookId = 5,
                            CoverImage = "cover 5",
                            Description = "Description 5",
                            EpubLink = "EpubLink5",
                            IsActive = true,
                            NumberOfPage = 500,
                            PdfLink = "PdfLink 5",
                            Price = 50.0,
                            ReleaseDate = new DateTime(2023, 2, 15, 10, 39, 55, 530, DateTimeKind.Local).AddTicks(5071),
                            SaleId = 5,
                            Title = "Book 5"
                        },
                        new
                        {
                            BookId = 6,
                            CoverImage = "cover 6",
                            Description = "Description 6",
                            EpubLink = "EpubLink6",
                            IsActive = true,
                            NumberOfPage = 600,
                            PdfLink = "PdfLink 6",
                            Price = 60.0,
                            ReleaseDate = new DateTime(2023, 2, 15, 10, 39, 55, 541, DateTimeKind.Local).AddTicks(8199),
                            SaleId = 6,
                            Title = "Book 6"
                        },
                        new
                        {
                            BookId = 7,
                            CoverImage = "cover 7",
                            Description = "Description 7",
                            EpubLink = "EpubLink7",
                            IsActive = true,
                            NumberOfPage = 700,
                            PdfLink = "PdfLink 7",
                            Price = 70.0,
                            ReleaseDate = new DateTime(2023, 2, 15, 10, 39, 55, 552, DateTimeKind.Local).AddTicks(9687),
                            SaleId = 7,
                            Title = "Book 7"
                        },
                        new
                        {
                            BookId = 8,
                            CoverImage = "cover 8",
                            Description = "Description 8",
                            EpubLink = "EpubLink8",
                            IsActive = true,
                            NumberOfPage = 800,
                            PdfLink = "PdfLink 8",
                            Price = 80.0,
                            ReleaseDate = new DateTime(2023, 2, 15, 10, 39, 55, 563, DateTimeKind.Local).AddTicks(9714),
                            SaleId = 8,
                            Title = "Book 8"
                        },
                        new
                        {
                            BookId = 9,
                            CoverImage = "cover 9",
                            Description = "Description 9",
                            EpubLink = "EpubLink9",
                            IsActive = true,
                            NumberOfPage = 900,
                            PdfLink = "PdfLink 9",
                            Price = 90.0,
                            ReleaseDate = new DateTime(2023, 2, 15, 10, 39, 55, 572, DateTimeKind.Local).AddTicks(9659),
                            SaleId = 9,
                            Title = "Book 9"
                        },
                        new
                        {
                            BookId = 10,
                            CoverImage = "cover 10",
                            Description = "Description 10",
                            EpubLink = "EpubLink10",
                            IsActive = true,
                            NumberOfPage = 1000,
                            PdfLink = "PdfLink 10",
                            Price = 100.0,
                            ReleaseDate = new DateTime(2023, 2, 15, 10, 39, 55, 579, DateTimeKind.Local).AddTicks(8811),
                            SaleId = 10,
                            Title = "Book 10"
                        });
                });

            modelBuilder.Entity("EbookStore.Contract.Model.CartItem", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef60"),
                            BookId = 1,
                            IsActive = false
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef61"),
                            BookId = 2,
                            IsActive = false
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef62"),
                            BookId = 3,
                            IsActive = false
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef63"),
                            BookId = 4,
                            IsActive = false
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef64"),
                            BookId = 5,
                            IsActive = false
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef65"),
                            BookId = 6,
                            IsActive = false
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef66"),
                            BookId = 7,
                            IsActive = false
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef67"),
                            BookId = 8,
                            IsActive = false
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef68"),
                            BookId = 9,
                            IsActive = false
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef69"),
                            BookId = 10,
                            IsActive = false
                        });
                });

            modelBuilder.Entity("EbookStore.Contract.Model.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            Name = "Genre 1"
                        },
                        new
                        {
                            GenreId = 2,
                            Name = "Genre 2"
                        },
                        new
                        {
                            GenreId = 3,
                            Name = "Genre 3"
                        },
                        new
                        {
                            GenreId = 4,
                            Name = "Genre 4"
                        },
                        new
                        {
                            GenreId = 5,
                            Name = "Genre 5"
                        },
                        new
                        {
                            GenreId = 6,
                            Name = "Genre 6"
                        },
                        new
                        {
                            GenreId = 7,
                            Name = "Genre 7"
                        },
                        new
                        {
                            GenreId = 8,
                            Name = "Genre 8"
                        },
                        new
                        {
                            GenreId = 9,
                            Name = "Genre 9"
                        },
                        new
                        {
                            GenreId = 10,
                            Name = "Genre 10"
                        });
                });

            modelBuilder.Entity("EbookStore.Contract.Model.LibraryItem", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("LibraryItems");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef60"),
                            BookId = 1
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef61"),
                            BookId = 2
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef62"),
                            BookId = 3
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef63"),
                            BookId = 4
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef64"),
                            BookId = 5
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef65"),
                            BookId = 6
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef66"),
                            BookId = 7
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef67"),
                            BookId = 8
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef68"),
                            BookId = 9
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef69"),
                            BookId = 10
                        });
                });

            modelBuilder.Entity("EbookStore.Contract.Model.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"), 1L, 1);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SalePercent")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SaleId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            SaleId = 1,
                            EndDate = new DateTime(2023, 2, 15, 10, 39, 55, 492, DateTimeKind.Local).AddTicks(6427),
                            Name = "Sale 1",
                            SalePercent = 1.0,
                            StartDate = new DateTime(2023, 2, 15, 10, 39, 55, 492, DateTimeKind.Local).AddTicks(6413)
                        },
                        new
                        {
                            SaleId = 2,
                            EndDate = new DateTime(2023, 2, 15, 10, 39, 55, 499, DateTimeKind.Local).AddTicks(5170),
                            Name = "Sale 2",
                            SalePercent = 2.0,
                            StartDate = new DateTime(2023, 2, 15, 10, 39, 55, 499, DateTimeKind.Local).AddTicks(5167)
                        },
                        new
                        {
                            SaleId = 3,
                            EndDate = new DateTime(2023, 2, 15, 10, 39, 55, 507, DateTimeKind.Local).AddTicks(504),
                            Name = "Sale 3",
                            SalePercent = 3.0,
                            StartDate = new DateTime(2023, 2, 15, 10, 39, 55, 507, DateTimeKind.Local).AddTicks(489)
                        },
                        new
                        {
                            SaleId = 4,
                            EndDate = new DateTime(2023, 2, 15, 10, 39, 55, 518, DateTimeKind.Local).AddTicks(8606),
                            Name = "Sale 4",
                            SalePercent = 4.0,
                            StartDate = new DateTime(2023, 2, 15, 10, 39, 55, 518, DateTimeKind.Local).AddTicks(8593)
                        },
                        new
                        {
                            SaleId = 5,
                            EndDate = new DateTime(2023, 2, 15, 10, 39, 55, 530, DateTimeKind.Local).AddTicks(5038),
                            Name = "Sale 5",
                            SalePercent = 5.0,
                            StartDate = new DateTime(2023, 2, 15, 10, 39, 55, 530, DateTimeKind.Local).AddTicks(5024)
                        },
                        new
                        {
                            SaleId = 6,
                            EndDate = new DateTime(2023, 2, 15, 10, 39, 55, 541, DateTimeKind.Local).AddTicks(8168),
                            Name = "Sale 6",
                            SalePercent = 6.0,
                            StartDate = new DateTime(2023, 2, 15, 10, 39, 55, 541, DateTimeKind.Local).AddTicks(8152)
                        },
                        new
                        {
                            SaleId = 7,
                            EndDate = new DateTime(2023, 2, 15, 10, 39, 55, 552, DateTimeKind.Local).AddTicks(9652),
                            Name = "Sale 7",
                            SalePercent = 7.0,
                            StartDate = new DateTime(2023, 2, 15, 10, 39, 55, 552, DateTimeKind.Local).AddTicks(9643)
                        },
                        new
                        {
                            SaleId = 8,
                            EndDate = new DateTime(2023, 2, 15, 10, 39, 55, 563, DateTimeKind.Local).AddTicks(9673),
                            Name = "Sale 8",
                            SalePercent = 8.0,
                            StartDate = new DateTime(2023, 2, 15, 10, 39, 55, 563, DateTimeKind.Local).AddTicks(9661)
                        },
                        new
                        {
                            SaleId = 9,
                            EndDate = new DateTime(2023, 2, 15, 10, 39, 55, 572, DateTimeKind.Local).AddTicks(9495),
                            Name = "Sale 9",
                            SalePercent = 9.0,
                            StartDate = new DateTime(2023, 2, 15, 10, 39, 55, 572, DateTimeKind.Local).AddTicks(9478)
                        },
                        new
                        {
                            SaleId = 10,
                            EndDate = new DateTime(2023, 2, 15, 10, 39, 55, 579, DateTimeKind.Local).AddTicks(8786),
                            Name = "Sale 10",
                            SalePercent = 10.0,
                            StartDate = new DateTime(2023, 2, 15, 10, 39, 55, 579, DateTimeKind.Local).AddTicks(8777)
                        });
                });

            modelBuilder.Entity("EbookStore.Contract.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef60"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "933ca9bd-efff-4033-a075-d8fe40851745",
                            Email = "user1@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Ten 1",
                            IsActive = true,
                            LastName = "Ho 1",
                            LockoutEnabled = false,
                            NormalizedEmail = "user1@gmail.com",
                            NormalizedUserName = "user1",
                            PasswordHash = "AQAAAAEAACcQAAAAEBUY5H6Pz1evbKWhaqX4F09GyF+j+tsPq5FJ5/j642NvVWrTSsInhGXJeEhYkwJwJA==",
                            PhoneNumber = "123456781",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "user1"
                        },
                        new
                        {
                            Id = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef61"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3c32e7d9-fef3-48c2-a5f3-c0795f98f2ad",
                            Email = "user2@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Ten 2",
                            IsActive = true,
                            LastName = "Ho 2",
                            LockoutEnabled = false,
                            NormalizedEmail = "user2@gmail.com",
                            NormalizedUserName = "user2",
                            PasswordHash = "AQAAAAEAACcQAAAAEEBqczvLLPwu7HFsLqGVVWjy7rX4zZZZLz9KttCc3oRZBWWJnNArtUTlzt0uoi9Tgg==",
                            PhoneNumber = "123456782",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "user2"
                        },
                        new
                        {
                            Id = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef62"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f8a71934-adee-451c-bc1d-ce8c704a73b7",
                            Email = "user3@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Ten 3",
                            IsActive = true,
                            LastName = "Ho 3",
                            LockoutEnabled = false,
                            NormalizedEmail = "user3@gmail.com",
                            NormalizedUserName = "user3",
                            PasswordHash = "AQAAAAEAACcQAAAAENMq8IBurT7WeSffswcN5PkWe3iDIgCJ9N/lECBQO+EYwYaBkuZTnsNZFKAhPrEZTA==",
                            PhoneNumber = "123456783",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "user3"
                        },
                        new
                        {
                            Id = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef63"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4f662376-6ae9-4c01-8ee6-15e17dbcbd37",
                            Email = "user4@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Ten 4",
                            IsActive = true,
                            LastName = "Ho 4",
                            LockoutEnabled = false,
                            NormalizedEmail = "user4@gmail.com",
                            NormalizedUserName = "user4",
                            PasswordHash = "AQAAAAEAACcQAAAAEMJqfhMKa6POMbdfJEEiybDkPcf6zSbK2kgzjuPZCxvdIGM4pTJAwWMDj8Oq9Hw+eQ==",
                            PhoneNumber = "123456784",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "user4"
                        },
                        new
                        {
                            Id = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef64"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "89a2011b-ba5a-4b83-916a-8555678647b9",
                            Email = "user5@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Ten 5",
                            IsActive = true,
                            LastName = "Ho 5",
                            LockoutEnabled = false,
                            NormalizedEmail = "user5@gmail.com",
                            NormalizedUserName = "user5",
                            PasswordHash = "AQAAAAEAACcQAAAAEH2znZMi+Hy23RRXzEy8WDmqMHYq6kPuYhu3lO7oqPPqaW035p9uXUop4WlwiRUJLg==",
                            PhoneNumber = "123456785",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "user5"
                        },
                        new
                        {
                            Id = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef65"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "39c535d1-dbbf-4958-bd79-678878405df9",
                            Email = "user6@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Ten 6",
                            IsActive = true,
                            LastName = "Ho 6",
                            LockoutEnabled = false,
                            NormalizedEmail = "user6@gmail.com",
                            NormalizedUserName = "user6",
                            PasswordHash = "AQAAAAEAACcQAAAAEJy9SevqFFb8moaaNg0MztC9pimuR9/ysfcUaOM1g66z/gz8Oi6t1LaojY4mAhhY+Q==",
                            PhoneNumber = "123456786",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "user6"
                        },
                        new
                        {
                            Id = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef66"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bf7768c3-4a92-4270-b18c-8d73ee915277",
                            Email = "user7@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Ten 7",
                            IsActive = true,
                            LastName = "Ho 7",
                            LockoutEnabled = false,
                            NormalizedEmail = "user7@gmail.com",
                            NormalizedUserName = "user7",
                            PasswordHash = "AQAAAAEAACcQAAAAEIuMj4SHIasUqGE6N/ALPJZXcAKGxyBgKcKtOGQMWGEmNWvCetgvyc3rv8k0W5GUYg==",
                            PhoneNumber = "123456787",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "user7"
                        },
                        new
                        {
                            Id = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef67"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "60df29b0-078a-4566-b6c2-efd65ef9b211",
                            Email = "user8@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Ten 8",
                            IsActive = true,
                            LastName = "Ho 8",
                            LockoutEnabled = false,
                            NormalizedEmail = "user8@gmail.com",
                            NormalizedUserName = "user8",
                            PasswordHash = "AQAAAAEAACcQAAAAEJTtJ2FKdodUab5en0Phs+Vq4yI5bn1yiJAt4s0N3/qoDT7a8yteV1tqL/h2pElp8A==",
                            PhoneNumber = "123456788",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "user8"
                        },
                        new
                        {
                            Id = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef68"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "51ec3460-1a95-4916-bc36-e056634adf63",
                            Email = "user9@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Ten 9",
                            IsActive = true,
                            LastName = "Ho 9",
                            LockoutEnabled = false,
                            NormalizedEmail = "user9@gmail.com",
                            NormalizedUserName = "user9",
                            PasswordHash = "AQAAAAEAACcQAAAAELZwPMmJUFm0XNjpJyvK5zYjIF9QzD8Sldd6GleQ86vtoB/hpQG9+F5PIvUhPCn2hA==",
                            PhoneNumber = "123456789",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "user9"
                        },
                        new
                        {
                            Id = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef69"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d6782091-c69f-42bb-ac07-68dd4f9bc2af",
                            Email = "user10@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Ten 10",
                            IsActive = true,
                            LastName = "Ho 10",
                            LockoutEnabled = false,
                            NormalizedEmail = "user10@gmail.com",
                            NormalizedUserName = "user10",
                            PasswordHash = "AQAAAAEAACcQAAAAEB/daZM4OCjE8Dm1O0xqabjRZp3gX3/vR9M6zFzPEnsj/1zNB35FMZlcPnwM9tY7uA==",
                            PhoneNumber = "1234567810",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "user10"
                        });
                });

            modelBuilder.Entity("EbookStore.Contract.Model.WishItem", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("WishItems");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef60"),
                            BookId = 1,
                            IsActive = false
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef61"),
                            BookId = 2,
                            IsActive = false
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef62"),
                            BookId = 3,
                            IsActive = false
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef63"),
                            BookId = 4,
                            IsActive = false
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef64"),
                            BookId = 5,
                            IsActive = false
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef65"),
                            BookId = 6,
                            IsActive = false
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef66"),
                            BookId = 7,
                            IsActive = false
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef67"),
                            BookId = 8,
                            IsActive = false
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef68"),
                            BookId = 9,
                            IsActive = false
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef69"),
                            BookId = 10,
                            IsActive = false
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef60"),
                            RoleId = new Guid("423e533c-d43d-4fd9-9676-e31af724522a")
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef61"),
                            RoleId = new Guid("da35db1a-5b54-4618-884e-bcd7f7b1dd19")
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef62"),
                            RoleId = new Guid("da35db1a-5b54-4618-884e-bcd7f7b1dd19")
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef63"),
                            RoleId = new Guid("da35db1a-5b54-4618-884e-bcd7f7b1dd19")
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef64"),
                            RoleId = new Guid("da35db1a-5b54-4618-884e-bcd7f7b1dd19")
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef65"),
                            RoleId = new Guid("da35db1a-5b54-4618-884e-bcd7f7b1dd19")
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef66"),
                            RoleId = new Guid("da35db1a-5b54-4618-884e-bcd7f7b1dd19")
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef67"),
                            RoleId = new Guid("da35db1a-5b54-4618-884e-bcd7f7b1dd19")
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef68"),
                            RoleId = new Guid("da35db1a-5b54-4618-884e-bcd7f7b1dd19")
                        },
                        new
                        {
                            UserId = new Guid("6baa519d-aaed-4190-a3c9-3c8f67ecef69"),
                            RoleId = new Guid("da35db1a-5b54-4618-884e-bcd7f7b1dd19")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.HasOne("EbookStore.Contract.Model.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EbookStore.Contract.Model.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresGenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EbookStore.Contract.Model.Book", b =>
                {
                    b.HasOne("EbookStore.Contract.Model.Sale", "Sale")
                        .WithMany("OnSaleBooks")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("EbookStore.Contract.Model.CartItem", b =>
                {
                    b.HasOne("EbookStore.Contract.Model.Book", "Book")
                        .WithMany("CartItems")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EbookStore.Contract.Model.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EbookStore.Contract.Model.LibraryItem", b =>
                {
                    b.HasOne("EbookStore.Contract.Model.Book", "Book")
                        .WithMany("LibraryItems")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EbookStore.Contract.Model.User", "User")
                        .WithMany("LibraryItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EbookStore.Contract.Model.WishItem", b =>
                {
                    b.HasOne("EbookStore.Contract.Model.Book", "Book")
                        .WithMany("WishItems")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EbookStore.Contract.Model.User", "User")
                        .WithMany("WishItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("EbookStore.Contract.Model.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("EbookStore.Contract.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("EbookStore.Contract.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("EbookStore.Contract.Model.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EbookStore.Contract.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("EbookStore.Contract.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EbookStore.Contract.Model.Book", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("LibraryItems");

                    b.Navigation("WishItems");
                });

            modelBuilder.Entity("EbookStore.Contract.Model.Sale", b =>
                {
                    b.Navigation("OnSaleBooks");
                });

            modelBuilder.Entity("EbookStore.Contract.Model.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("LibraryItems");

                    b.Navigation("WishItems");
                });
#pragma warning restore 612, 618
        }
    }
}
